name: nordiccodeacademy
favicon: null
layout_spectrum: 0.8964372002519667
typography_spectrum: 0.43924174597486854
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.47336317668668926
  lightness: 0.7960255574434996
  saturation: 0.8147191405296326
  rhythmicContrast: 0.46390860015526414
purpose: []
